[package]
name = "dkill"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]

[dependencies]
clap = { version = "*", features = ["unstable", "suggestions", "color"] }
clippy = "*"
regex = "*"
sha1 = "*"
walkdir = "*"
